### ISSUE TITLE
Fossa CLI error

### ISSUE THREAD

**Issue by soneillf5** [fossas/fossa-action#10]
Hi,

I just came across the following error, if you could take a look that would be great.

We use the following config:

```
jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
```
Which gives us an error:
``` There was an error fetching FOSSA CLI. TypeError: Cannot read property '1' of null```

I think this is coming from 
```
function fetchFossaCli() {
...
    const version = versionExecOut.match(/version (\d.\d.\d)/)[1] || 'nover';
```

I think the intent is that if there is no match in the version regex, it returns false and version is set to 'nover', but if I run the js myself I get:
```
"1.2.3".match(/version (\d.\d.\d)/)
null
```
and then we see the `[1]` attempt to access null.

I'm not sure if this is the underlying cause, but it's a bug either way.
