### ISSUE TITLE
Support for custom properties passed to the action

### ISSUE THREAD

**Issue by cmboling** [fossas/fossa-action#21]
Include a field to add custom properties to FOSSA analysis. Some users are dealing with custom builds which require custom properties to be passed to the invocation.

@nielsdoucet provided a use case where a custom gradle wrapper is used where custom system properties are passed (e.g. `./gradlew -Dany.system.prop=value`)

```
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.fossaApiKey}}
          - gradle:
            - system-properties:
              sys.prop1: value1
              sys.prop2: value2
            - properties:
              prop1: value1
              prop2: value2
```
