### ISSUE TITLE
fs undefined reading createWriteStream

### ISSUE THREAD

**Issue by anibe** [fossas/fossa-action#22]
Hello,

We recently noticed our builds failing the FOSSA scan due to the error below:

```
Run fossas/fossa-action@main
Error: There was an error fetching FOSSA CLI. TypeError: Cannot read properties of undefined (reading 'createWriteStream')
```

It appears to have been introduced [with v1.2.0](https://github.com/fossas/fossa-action/pull/19/files#diff-ad7faa452db2c39d404f11b420fb4ce38631c8b04c45f666320ba08fe371ff8a).

Could you please consider offering backward compatibility for build agents that don't support the new Node.js syntax?

Details of our GitHub Action runner below:
Operating System:
  Ubuntu

  LTS
Virtual Environment:
  Environment: ubuntu-20.04
  Version: 20220410.2

**Comment by DavidGoodwin** [comment]
(Same here)

**Comment by rayanht** [comment]
(Same here)

**Comment by rayanht** [comment]
Same here,

As a temporary workaround, you can pin the FOSSA action version like this:

```
      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
```
