### ISSUE TITLE
Input required and not supplied: api-key

### ISSUE THREAD

**Issue by zhujian7** [fossas/fossa-action#62]
I have an organization secret `FOSSA_API_KEY`, but still get an error `Input required and not supplied: api-key`: 
```
/home/runner/work/_actions/fossas/fossa-action/main/node_modules/@actions/core/lib/core.js:106
        throw new Error(`Input required and not supplied: ${name}`);
^
Error: Input required and not supplied: api-key
```

Here is my action yaml:
```
name: FOSSA License Scanning

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: read
  actions: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ env.fossa_api_key }}
          debug: true
```
Any suggestions?

**Comment by pieterocp** [comment]
From the information you've provided, the most likely issue looks like the `api-key` needs setting with a key and some SCREAMING_SNAKE_CASE? e.g. swap it out for:

```yaml
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secret.FOSSA_API_KEY}}
          debug: true
```
